version: '3.4'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    environment: 
            - APACHE_RUN_USER=#1000
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    working_dir: /var/www/web/assets
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: yiieventerDB
    volumes:
        - ./databases:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  composer:
    image: composer:2.1.12
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    working_dir: /var/www/web/assets
    command: composer install
